ALTER TABLE "radius_sync"."artifacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."event_artifacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."file_artifacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."link_artifacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."changes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."devices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_run_presentations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_run_state_updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."approval_decisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."approval_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."errors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."message_parts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."reasoning_summaries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."session_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_step_updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_steps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_calls" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_progress_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_results" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."file_changes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."project_file_versions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."project_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "artifacts_membership_isolation" ON "radius_sync"."artifacts" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "event_artifacts_membership_isolation" ON "radius_sync"."event_artifacts" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = event_artifacts.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = event_artifacts.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "file_artifacts_membership_isolation" ON "radius_sync"."file_artifacts" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "link_artifacts_membership_isolation" ON "radius_sync"."link_artifacts" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.artifacts owner_artifact where owner_artifact.artifact_id = link_artifacts.artifact_id and owner_artifact.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.artifacts owner_artifact where owner_artifact.artifact_id = link_artifacts.artifact_id and owner_artifact.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "changes_membership_isolation" ON "radius_sync"."changes" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "devices_membership_isolation" ON "radius_sync"."devices" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "projects_membership_isolation" ON "radius_sync"."projects" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "sessions_membership_isolation" ON "radius_sync"."sessions" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "agent_run_presentations_membership_isolation" ON "radius_sync"."agent_run_presentations" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_run_presentations.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_run_presentations.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "agent_run_state_updates_membership_isolation" ON "radius_sync"."agent_run_state_updates" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_run_state_updates.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_run_state_updates.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "agent_runs_membership_isolation" ON "radius_sync"."agent_runs" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_runs.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = agent_runs.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "approval_decisions_membership_isolation" ON "radius_sync"."approval_decisions" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = approval_decisions.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = approval_decisions.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "approval_requests_membership_isolation" ON "radius_sync"."approval_requests" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = approval_requests.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = approval_requests.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "errors_membership_isolation" ON "radius_sync"."errors" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = errors.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = errors.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "message_parts_membership_isolation" ON "radius_sync"."message_parts" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = message_parts.message_event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = message_parts.message_event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "messages_membership_isolation" ON "radius_sync"."messages" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = messages.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = messages.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "reasoning_summaries_membership_isolation" ON "radius_sync"."reasoning_summaries" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = reasoning_summaries.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = reasoning_summaries.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "session_events_membership_isolation" ON "radius_sync"."session_events" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "task_plans_membership_isolation" ON "radius_sync"."task_plans" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = task_plans.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = task_plans.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "task_step_updates_membership_isolation" ON "radius_sync"."task_step_updates" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = task_step_updates.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = task_step_updates.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "task_steps_membership_isolation" ON "radius_sync"."task_steps" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.task_plans owner_plan join radius_sync.session_events owner_event on owner_event.event_id = owner_plan.event_id where owner_plan.plan_id = task_steps.plan_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.task_plans owner_plan join radius_sync.session_events owner_event on owner_event.event_id = owner_plan.event_id where owner_plan.plan_id = task_steps.plan_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "tool_calls_membership_isolation" ON "radius_sync"."tool_calls" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_calls.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_calls.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "tool_progress_events_membership_isolation" ON "radius_sync"."tool_progress_events" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_progress_events.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_progress_events.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "tool_results_membership_isolation" ON "radius_sync"."tool_results" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_results.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = tool_results.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "file_changes_membership_isolation" ON "radius_sync"."file_changes" AS PERMISSIVE FOR ALL TO public USING (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = file_changes.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid)) WITH CHECK (exists (select 1 from radius_sync.session_events owner_event where owner_event.event_id = file_changes.event_id and owner_event.membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid));--> statement-breakpoint
CREATE POLICY "project_file_versions_membership_isolation" ON "radius_sync"."project_file_versions" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "project_files_membership_isolation" ON "radius_sync"."project_files" AS PERMISSIVE FOR ALL TO public USING (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid) WITH CHECK (membership_id = nullif(current_setting('radius_sync.membership_id', true), '')::uuid);
-- The platform API connects as the role that owns these tables, and owners
-- bypass row security unless it is forced. Forced, the policies bind the
-- owner too; referential actions such as membership cascades still run.
ALTER TABLE "radius_sync"."artifacts" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."event_artifacts" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."file_artifacts" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."link_artifacts" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."changes" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."devices" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."projects" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."sessions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_run_presentations" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_run_state_updates" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."agent_runs" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."approval_decisions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."approval_requests" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."errors" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."message_parts" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."messages" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."reasoning_summaries" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."session_events" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_plans" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_step_updates" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."task_steps" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_calls" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_progress_events" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."tool_results" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."file_changes" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."project_file_versions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radius_sync"."project_files" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
